Repository engity-com/bifroest, pull requests merged in 2024-10, with the labels that each got.

#19 Typos
  README.md
  docs/.theme/marcos/main.py
  docs/community/contributing.md
  docs/community/index.md
  docs/index.md
  docs/reference/authorization/htpasswd.md
  docs/reference/authorization/index.md
  docs/reference/authorization/local.md
  docs/reference/authorization/oidc.md
  docs/reference/authorization/simple.md
  docs/reference/configuration.md
  docs/reference/connection/ssh.md
  docs/reference/context/authorization.md
  docs/reference/context/oidc-id-token.md
  docs/reference/context/oidc-user-info.md
  docs/reference/environment/index.md
  docs/reference/environment/local.md
  docs/reference/flow.md
  docs/reference/session/fs.md
  docs/setup/distribution.md
  docs/setup/index.md
  docs/setup/security.md
  docs/usecases.md
Labels: documentation, accepted, test_publish

#22 Basic documentation how to obtain the images.
  docs/.theme/marcos/main.py
  docs/setup/distribution.md
  docs/setup/index.md
Labels: documentation, accepted

#24 Improve PR Update workflow
  .github/workflows/pr-update.yml
  cmd/build/repo-prs.go
Labels: bug, accepted, github_actions

#25 Fixed ca-certs generation
  cmd/build/dependencies-ca-certs.go
  pkg/crypto/ca-certs.crt
Labels: bug, go, accepted
